#!/usr/bin/env bash
# Displays numbers and fizzbuzz

for (( count = 1; count <= 100; count++))
do
	if [ $((count % 3)) -eq 0 ] && [ $((count % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((count % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((count % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo $count
	fi
done
