#!/usr/bin/env bash
# Use while loop and if-elif-else conditions

str='Best School'
count=0

while echo "$str"
	[ $count -lt 7 ]
do
	if [ $count -eq 2 ]
	then
		echo "bad luck"
	elif [ $count -eq 5 ]
	then
		echo "good luck"
	fi
	count=$((count + 1))
done
