#!/usr/bin/env bash
# Implement the case statement

count=1

while echo "$count"
	[ $count -lt 20 ]
do
	case $count in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	count=$((count + 1))
done
